//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dimensions.Converter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PhysicsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PhysicsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dimensions.Converter.Properties.PhysicsResources", typeof(PhysicsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to •.
        /// </summary>
        public static string DotOperator {
            get {
                return ResourceManager.GetString("DotOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centi.
        /// </summary>
        public static string MultipleNameCenti {
            get {
                return ResourceManager.GetString("MultipleNameCenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deca.
        /// </summary>
        public static string MultipleNameDeca {
            get {
                return ResourceManager.GetString("MultipleNameDeca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deci.
        /// </summary>
        public static string MultipleNameDeci {
            get {
                return ResourceManager.GetString("MultipleNameDeci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to femto.
        /// </summary>
        public static string MultipleNameFemto {
            get {
                return ResourceManager.GetString("MultipleNameFemto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to giga.
        /// </summary>
        public static string MultipleNameGiga {
            get {
                return ResourceManager.GetString("MultipleNameGiga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hecto.
        /// </summary>
        public static string MultipleNameHecto {
            get {
                return ResourceManager.GetString("MultipleNameHecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilo.
        /// </summary>
        public static string MultipleNameKilo {
            get {
                return ResourceManager.GetString("MultipleNameKilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mega.
        /// </summary>
        public static string MultipleNameMega {
            get {
                return ResourceManager.GetString("MultipleNameMega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to micro.
        /// </summary>
        public static string MultipleNameMicro {
            get {
                return ResourceManager.GetString("MultipleNameMicro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milli.
        /// </summary>
        public static string MultipleNameMilli {
            get {
                return ResourceManager.GetString("MultipleNameMilli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nano.
        /// </summary>
        public static string MultipleNameNano {
            get {
                return ResourceManager.GetString("MultipleNameNano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pico.
        /// </summary>
        public static string MultipleNamePico {
            get {
                return ResourceManager.GetString("MultipleNamePico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tera.
        /// </summary>
        public static string MultipleNameTera {
            get {
                return ResourceManager.GetString("MultipleNameTera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c.
        /// </summary>
        public static string MultipleSymbolCenti {
            get {
                return ResourceManager.GetString("MultipleSymbolCenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da.
        /// </summary>
        public static string MultipleSymbolDeca {
            get {
                return ResourceManager.GetString("MultipleSymbolDeca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string MultipleSymbolDeci {
            get {
                return ResourceManager.GetString("MultipleSymbolDeci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.
        /// </summary>
        public static string MultipleSymbolFemto {
            get {
                return ResourceManager.GetString("MultipleSymbolFemto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        public static string MultipleSymbolGiga {
            get {
                return ResourceManager.GetString("MultipleSymbolGiga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string MultipleSymbolHecto {
            get {
                return ResourceManager.GetString("MultipleSymbolHecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to k.
        /// </summary>
        public static string MultipleSymbolKilo {
            get {
                return ResourceManager.GetString("MultipleSymbolKilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string MultipleSymbolMega {
            get {
                return ResourceManager.GetString("MultipleSymbolMega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to µ.
        /// </summary>
        public static string MultipleSymbolMicro {
            get {
                return ResourceManager.GetString("MultipleSymbolMicro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string MultipleSymbolMilli {
            get {
                return ResourceManager.GetString("MultipleSymbolMilli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        public static string MultipleSymbolNano {
            get {
                return ResourceManager.GetString("MultipleSymbolNano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p.
        /// </summary>
        public static string MultipleSymbolPico {
            get {
                return ResourceManager.GetString("MultipleSymbolPico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string MultipleSymbolTera {
            get {
                return ResourceManager.GetString("MultipleSymbolTera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acceleration.
        /// </summary>
        public static string NameAcceleration {
            get {
                return ResourceManager.GetString("NameAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ampere.
        /// </summary>
        public static string NameAmpere {
            get {
                return ResourceManager.GetString("NameAmpere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed constant.
        /// </summary>
        public static string NameAngularFeedConstant {
            get {
                return ResourceManager.GetString("NameAngularFeedConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to angular momentum.
        /// </summary>
        public static string NameAngularMomentum {
            get {
                return ResourceManager.GetString("NameAngularMomentum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to angular speed.
        /// </summary>
        public static string NameAngularSpeed {
            get {
                return ResourceManager.GetString("NameAngularSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to area.
        /// </summary>
        public static string NameArea {
            get {
                return ResourceManager.GetString("NameArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to capacity.
        /// </summary>
        public static string NameCapacity {
            get {
                return ResourceManager.GetString("NameCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to celsius.
        /// </summary>
        public static string NameCelsius {
            get {
                return ResourceManager.GetString("NameCelsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coulomb.
        /// </summary>
        public static string NameCoulomb {
            get {
                return ResourceManager.GetString("NameCoulomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current.
        /// </summary>
        public static string NameCurrent {
            get {
                return ResourceManager.GetString("NameCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current density.
        /// </summary>
        public static string NameCurrentDensity {
            get {
                return ResourceManager.GetString("NameCurrentDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to density.
        /// </summary>
        public static string NameDensity {
            get {
                return ResourceManager.GetString("NameDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed constant.
        /// </summary>
        public static string NameDistanceFeedConstant {
            get {
                return ResourceManager.GetString("NameDistanceFeedConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to electric charge.
        /// </summary>
        public static string NameElectricCharge {
            get {
                return ResourceManager.GetString("NameElectricCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        public static string NameFahrenheit {
            get {
                return ResourceManager.GetString("NameFahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed constant.
        /// </summary>
        public static string NameFeedConstant {
            get {
                return ResourceManager.GetString("NameFeedConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to force.
        /// </summary>
        public static string NameForce {
            get {
                return ResourceManager.GetString("NameForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed constant.
        /// </summary>
        public static string NameGeneralFeedConstant {
            get {
                return ResourceManager.GetString("NameGeneralFeedConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string NameGenericUnit {
            get {
                return ResourceManager.GetString("NameGenericUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Henry.
        /// </summary>
        public static string NameHenry {
            get {
                return ResourceManager.GetString("NameHenry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inductance.
        /// </summary>
        public static string NameInductance {
            get {
                return ResourceManager.GetString("NameInductance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inertia.
        /// </summary>
        public static string NameInertia {
            get {
                return ResourceManager.GetString("NameInertia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerk.
        /// </summary>
        public static string NameJerk {
            get {
                return ResourceManager.GetString("NameJerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length.
        /// </summary>
        public static string NameLength {
            get {
                return ResourceManager.GetString("NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mass.
        /// </summary>
        public static string NameMass {
            get {
                return ResourceManager.GetString("NameMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to percent.
        /// </summary>
        public static string NamePercent {
            get {
                return ResourceManager.GetString("NamePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plane angle.
        /// </summary>
        public static string NamePlaneAngle {
            get {
                return ResourceManager.GetString("NamePlaneAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to power.
        /// </summary>
        public static string NamePower {
            get {
                return ResourceManager.GetString("NamePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radiant.
        /// </summary>
        public static string NameRad {
            get {
                return ResourceManager.GetString("NameRad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        public static string NameRatio {
            get {
                return ResourceManager.GetString("NameRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resistance.
        /// </summary>
        public static string NameResistance {
            get {
                return ResourceManager.GetString("NameResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rotation.
        /// </summary>
        public static string NameRotation {
            get {
                return ResourceManager.GetString("NameRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rotational speed.
        /// </summary>
        public static string NameRotationalSpeed {
            get {
                return ResourceManager.GetString("NameRotationalSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solid angle.
        /// </summary>
        public static string NameSolidAngle {
            get {
                return ResourceManager.GetString("NameSolidAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speed.
        /// </summary>
        public static string NameSpeed {
            get {
                return ResourceManager.GetString("NameSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steradiant.
        /// </summary>
        public static string NameSr {
            get {
                return ResourceManager.GetString("NameSr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temperature.
        /// </summary>
        public static string NameTemperature {
            get {
                return ResourceManager.GetString("NameTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelvin.
        /// </summary>
        public static string NameTemperatureKelvin {
            get {
                return ResourceManager.GetString("NameTemperatureKelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string NameTime {
            get {
                return ResourceManager.GetString("NameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ton.
        /// </summary>
        public static string NameTon {
            get {
                return ResourceManager.GetString("NameTon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to torque.
        /// </summary>
        public static string NameTorque {
            get {
                return ResourceManager.GetString("NameTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to velocity.
        /// </summary>
        public static string NameVelocity {
            get {
                return ResourceManager.GetString("NameVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viscosity.
        /// </summary>
        public static string NameViscosity {
            get {
                return ResourceManager.GetString("NameViscosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viscous force.
        /// </summary>
        public static string NameViscousForce {
            get {
                return ResourceManager.GetString("NameViscousForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viscous torque.
        /// </summary>
        public static string NameViscousTorque {
            get {
                return ResourceManager.GetString("NameViscousTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to voltage.
        /// </summary>
        public static string NameVoltage {
            get {
                return ResourceManager.GetString("NameVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volume.
        /// </summary>
        public static string NameVolume {
            get {
                return ResourceManager.GetString("NameVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weight.
        /// </summary>
        public static string NameWeight {
            get {
                return ResourceManager.GetString("NameWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to work.
        /// </summary>
        public static string NameWork {
            get {
                return ResourceManager.GetString("NameWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¹.
        /// </summary>
        public static string SuperScript1 {
            get {
                return ResourceManager.GetString("SuperScript1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ².
        /// </summary>
        public static string SuperScript2 {
            get {
                return ResourceManager.GetString("SuperScript2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ³.
        /// </summary>
        public static string SuperScript3 {
            get {
                return ResourceManager.GetString("SuperScript3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⁴.
        /// </summary>
        public static string SuperScript4 {
            get {
                return ResourceManager.GetString("SuperScript4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⁻.
        /// </summary>
        public static string SuperScriptMinus {
            get {
                return ResourceManager.GetString("SuperScriptMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string SymbolAcceleration {
            get {
                return ResourceManager.GetString("SymbolAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string SymbolAmpere {
            get {
                return ResourceManager.GetString("SymbolAmpere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °.
        /// </summary>
        public static string SymbolAngleDegree {
            get {
                return ResourceManager.GetString("SymbolAngleDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        public static string SymbolCelsius {
            get {
                return ResourceManager.GetString("SymbolCelsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string SymbolCoulomb {
            get {
                return ResourceManager.GetString("SymbolCoulomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        public static string SymbolCurrent {
            get {
                return ResourceManager.GetString("SymbolCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string SymbolDay {
            get {
                return ResourceManager.GetString("SymbolDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string SymbolFahrenheit {
            get {
                return ResourceManager.GetString("SymbolFahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string SymbolFarad {
            get {
                return ResourceManager.GetString("SymbolFarad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        public static string SymbolFoot {
            get {
                return ResourceManager.GetString("SymbolFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        public static string SymbolGram {
            get {
                return ResourceManager.GetString("SymbolGram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        public static string SymbolHenry {
            get {
                return ResourceManager.GetString("SymbolHenry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string SymbolHour {
            get {
                return ResourceManager.GetString("SymbolHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string SymbolInch {
            get {
                return ResourceManager.GetString("SymbolInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l.
        /// </summary>
        public static string SymbolLength {
            get {
                return ResourceManager.GetString("SymbolLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l.
        /// </summary>
        public static string SymbolLitre {
            get {
                return ResourceManager.GetString("SymbolLitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string SymbolMeter {
            get {
                return ResourceManager.GetString("SymbolMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        public static string SymbolMile {
            get {
                return ResourceManager.GetString("SymbolMile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string SymbolMinute {
            get {
                return ResourceManager.GetString("SymbolMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string SymbolNewton {
            get {
                return ResourceManager.GetString("SymbolNewton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ω.
        /// </summary>
        public static string SymbolOhm {
            get {
                return ResourceManager.GetString("SymbolOhm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string SymbolPercent {
            get {
                return ResourceManager.GetString("SymbolPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb.
        /// </summary>
        public static string SymbolPound {
            get {
                return ResourceManager.GetString("SymbolPound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        public static string SymbolPower {
            get {
                return ResourceManager.GetString("SymbolPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rad.
        /// </summary>
        public static string SymbolRad {
            get {
                return ResourceManager.GetString("SymbolRad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string SymbolRotation {
            get {
                return ResourceManager.GetString("SymbolRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ω.
        /// </summary>
        public static string SymbolRotationalSpeed {
            get {
                return ResourceManager.GetString("SymbolRotationalSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string SymbolSecond {
            get {
                return ResourceManager.GetString("SymbolSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ω.
        /// </summary>
        public static string SymbolSr {
            get {
                return ResourceManager.GetString("SymbolSr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string SymbolTemperature {
            get {
                return ResourceManager.GetString("SymbolTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        public static string SymbolTemperatureKelvin {
            get {
                return ResourceManager.GetString("SymbolTemperatureKelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t.
        /// </summary>
        public static string SymbolTime {
            get {
                return ResourceManager.GetString("SymbolTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t.
        /// </summary>
        public static string SymbolTon {
            get {
                return ResourceManager.GetString("SymbolTon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        public static string SymbolVolt {
            get {
                return ResourceManager.GetString("SymbolVolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string SymbolWatt {
            get {
                return ResourceManager.GetString("SymbolWatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yd.
        /// </summary>
        public static string SymbolYard {
            get {
                return ResourceManager.GetString("SymbolYard", resourceCulture);
            }
        }
    }
}
